package main

import (
	"bytes"
	"context"
	"flag"
	"fmt"
	"net"
	"net/http"
	"sync"
	"testing"
	"time"

	"github.com/gorilla/mux"
	"github.com/stretchr/testify/suite"
	"github.com/urfave/cli/v2"
	"go.uber.org/zap"
)

type ProxyE2ETestSuite struct {
	suite.Suite

	// ProxyPort define on which port the proxy is currently listening
	ProxyUrl          string
	TrueNASMockServer http.Server
}

func (s *ProxyE2ETestSuite) SetupSuite() {
	// Configure TrueNASMockServer
	lmock, err := net.Listen("tcp", ":0")
	s.Require().NoError(err)

	r := mux.NewRouter()
	// NOTE: enable authentication on all path
	r.Use(func(handler http.Handler) http.Handler {
		return http.HandlerFunc(func(w http.ResponseWriter, req *http.Request) {
			if req.Header.Get("Authorization") != "Bearer token" {
				w.WriteHeader(http.StatusUnauthorized)
				return
			}
			handler.ServeHTTP(w, req)
		})
	})
	// NOTE: force this path to be slow for cache testing
	r.Methods(http.MethodPost).
		Path("/api/v2.0/filesystem/listdir").
		HandlerFunc(func(w http.ResponseWriter, _ *http.Request) {
			time.Sleep(500 * time.Millisecond)
			w.WriteHeader(http.StatusOK)
		})
	r.PathPrefix("/api/v2.0/").HandlerFunc(func(w http.ResponseWriter, _ *http.Request) { w.WriteHeader(http.StatusOK) })
	s.TrueNASMockServer.Handler = r
	go func(s *ProxyE2ETestSuite) { _ = s.TrueNASMockServer.Serve(lmock) }(s)

	// Configure Proxy-API
	lproxy, err := net.Listen("tcp", ":0")
	s.Require().NoError(err)
	s.Require().NoError(lproxy.Close())

	s.ProxyUrl = fmt.Sprintf("http://localhost:%d", lproxy.Addr().(*net.TCPAddr).Port)

	fs := &flag.FlagSet{}
	fs.String("truenas.url", fmt.Sprintf("http://localhost:%d", lmock.Addr().(*net.TCPAddr).Port), "")
	fs.String("truenas.token", "token", "")
	fs.String("listen.addr", fmt.Sprintf(":%d", lproxy.Addr().(*net.TCPAddr).Port), "")
	go func(s *ProxyE2ETestSuite) {
		s.Require().NoError(ProxyAction(zap.NewNop())(cli.NewContext(nil, fs, nil)))
	}(s)
}

func (s *ProxyE2ETestSuite) TearDownSuite() {
	s.Require().NoError(s.TrueNASMockServer.Shutdown(context.Background()))
}

func (s *ProxyE2ETestSuite) TestAuthorizedPaths() {
	for method, paths := range trueNASOpenAPIPaths {
		for target, code := range paths {
			s.Run(method+target, func() {
				req, err := http.NewRequest(method, s.ProxyUrl+target, bytes.NewBuffer(nil))
				s.Require().NoError(err)

				resp, err := http.DefaultClient.Do(req)
				s.Require().NoError(err)

				s.Assert().Equal(code, resp.StatusCode)
			})
		}
	}
}

func (s *ProxyE2ETestSuite) TestCache() {
	reqA, err := http.NewRequest(http.MethodPost, s.ProxyUrl+"/truenas/api/v2.0/filesystem/listdir", bytes.NewBuffer([]byte(`payloadA`)))
	s.Require().NoError(err)
	reqB, err := http.NewRequest(http.MethodPost, s.ProxyUrl+"/truenas/api/v2.0/filesystem/listdir", bytes.NewBuffer([]byte(`payloadB`)))
	s.Require().NoError(err)

	s.Assert().Never(func() bool {
		_, err := http.DefaultClient.Do(reqA)
		return s.Assert().NoError(err)
	}, 200*time.Millisecond, 50*time.Millisecond)

	// NOTE: give the time to the precedent request to finish properly and to cache the request
	time.Sleep(500 * time.Millisecond)

	s.Assert().Eventually(func() bool {
		_, err := http.DefaultClient.Do(reqA)
		return s.Assert().NoError(err)
	}, 200*time.Millisecond, 50*time.Millisecond)

	// NOTE: because the cache depends on body when using POST, the reqB should not be cached
	s.Assert().Never(func() bool {
		_, err := http.DefaultClient.Do(reqB)
		return s.Assert().NoError(err)
	}, 200*time.Millisecond, 50*time.Millisecond)
}

func (s *ProxyE2ETestSuite) TestRaceCondition() {
	wg := sync.WaitGroup{}
	for path := range trueNASOpenAPIPaths[http.MethodGet] {
		wg.Add(1)
		go func(path string) {
			_, _ = http.Get(s.ProxyUrl + path)
			wg.Done()
		}(path)
	}
	wg.Wait()
}

func TestProxyE2ETestSuite(t *testing.T) { suite.Run(t, new(ProxyE2ETestSuite)) }

// trueNASOpenAPIPaths is an inventory of all paths defined inside the TrueNAS OpenAPI
var trueNASOpenAPIPaths = map[string]map[string]int{
	http.MethodDelete: {
		"/truenas/api/v2.0/acme/dns/authenticator/id/{id}": http.StatusUnauthorized,
		"/truenas/api/v2.0/alertservice/id/{id}":           http.StatusUnauthorized,
		"/truenas/api/v2.0/api_key/id/{id}":                http.StatusUnauthorized,
		"/truenas/api/v2.0/bootenv/id/{id}":                http.StatusUnauthorized,
		"/truenas/api/v2.0/catalog/id/{id}":                http.StatusUnauthorized,
		"/truenas/api/v2.0/certificate/id/{id}":            http.StatusUnauthorized,
		"/truenas/api/v2.0/certificateauthority/id/{id}":   http.StatusUnauthorized,
		"/truenas/api/v2.0/chart/release/id/{id}":          http.StatusUnauthorized,
		"/truenas/api/v2.0/cloudsync/id/{id}":              http.StatusUnauthorized,
		"/truenas/api/v2.0/cloudsync/credentials/id/{id}":  http.StatusUnauthorized,
		"/truenas/api/v2.0/container/image/id/{id}":        http.StatusUnauthorized,
		"/truenas/api/v2.0/cronjob/id/{id}":                http.StatusUnauthorized,
		"/truenas/api/v2.0/ctdb/public/ips/id/{id}":        http.StatusUnauthorized,
		"/truenas/api/v2.0/filesystem/acltemplate/id/{id}": http.StatusUnauthorized,
		"/truenas/api/v2.0/gluster/peer/id/{id}":           http.StatusUnauthorized,
		"/truenas/api/v2.0/gluster/volume/id/{id}":         http.StatusUnauthorized,
		"/truenas/api/v2.0/group/id/{id}":                  http.StatusUnauthorized,
		"/truenas/api/v2.0/idmap/id/{id}":                  http.StatusUnauthorized,
		"/truenas/api/v2.0/initshutdownscript/id/{id}":     http.StatusUnauthorized,
		"/truenas/api/v2.0/interface/id/{id}":              http.StatusUnauthorized,
		"/truenas/api/v2.0/iscsi/auth/id/{id}":             http.StatusUnauthorized,
		"/truenas/api/v2.0/iscsi/extent/id/{id}":           http.StatusUnauthorized,
		"/truenas/api/v2.0/iscsi/host/id/{id}":             http.StatusUnauthorized,
		"/truenas/api/v2.0/iscsi/initiator/id/{id}":        http.StatusUnauthorized,
		"/truenas/api/v2.0/iscsi/portal/id/{id}":           http.StatusUnauthorized,
		"/truenas/api/v2.0/iscsi/target/id/{id}":           http.StatusUnauthorized,
		"/truenas/api/v2.0/iscsi/targetextent/id/{id}":     http.StatusUnauthorized,
		"/truenas/api/v2.0/kerberos/keytab/id/{id}":        http.StatusUnauthorized,
		"/truenas/api/v2.0/kerberos/realm/id/{id}":         http.StatusUnauthorized,
		"/truenas/api/v2.0/keychaincredential/id/{id}":     http.StatusUnauthorized,
		"/truenas/api/v2.0/pool/dataset/id/{id}":           http.StatusUnauthorized,
		"/truenas/api/v2.0/pool/dataset/userprop/id/{id}":  http.StatusUnauthorized,
		"/truenas/api/v2.0/pool/scrub/id/{id}":             http.StatusUnauthorized,
		"/truenas/api/v2.0/pool/snapshottask/id/{id}":      http.StatusUnauthorized,
		"/truenas/api/v2.0/replication/id/{id}":            http.StatusUnauthorized,
		"/truenas/api/v2.0/rsyncmod/id/{id}":               http.StatusUnauthorized,
		"/truenas/api/v2.0/rsynctask/id/{id}":              http.StatusUnauthorized,
		"/truenas/api/v2.0/sharing/nfs/id/{id}":            http.StatusUnauthorized,
		"/truenas/api/v2.0/sharing/smb/id/{id}":            http.StatusUnauthorized,
		"/truenas/api/v2.0/sharing/webdav/id/{id}":         http.StatusUnauthorized,
		"/truenas/api/v2.0/smart/test/id/{id}":             http.StatusUnauthorized,
		"/truenas/api/v2.0/smb/sharesec/id/{id}":           http.StatusUnauthorized,
		"/truenas/api/v2.0/staticroute/id/{id}":            http.StatusUnauthorized,
		"/truenas/api/v2.0/system/ntpserver/id/{id}":       http.StatusUnauthorized,
		"/truenas/api/v2.0/tunable/id/{id}":                http.StatusUnauthorized,
		"/truenas/api/v2.0/user/id/{id}":                   http.StatusUnauthorized,
		"/truenas/api/v2.0/vm/id/{id}":                     http.StatusUnauthorized,
		"/truenas/api/v2.0/vm/device/id/{id}":              http.StatusUnauthorized,
		"/truenas/api/v2.0/vmware/id/{id}":                 http.StatusUnauthorized,
		"/truenas/api/v2.0/webui/image/id/{id}":            http.StatusUnauthorized,
		"/truenas/api/v2.0/zfs/snapshot/id/{id}":           http.StatusUnauthorized,
	},
	http.MethodGet: {
		"/truenas/api/v2.0/core/debug_mode_enabled":                              http.StatusUnauthorized,
		"/truenas/api/v2.0/core/get_events":                                      http.StatusUnauthorized,
		"/truenas/api/v2.0/core/get_jobs":                                        http.StatusUnauthorized,
		"/truenas/api/v2.0/core/get_websocket_messages":                          http.StatusUnauthorized,
		"/truenas/api/v2.0/core/ping":                                            http.StatusUnauthorized,
		"/truenas/api/v2.0/core/sessions":                                        http.StatusUnauthorized,
		"/truenas/api/v2.0/acme/dns/authenticator":                               http.StatusUnauthorized,
		"/truenas/api/v2.0/acme/dns/authenticator/id/{id}":                       http.StatusUnauthorized,
		"/truenas/api/v2.0/acme/dns/authenticator/authenticator_schemas":         http.StatusUnauthorized,
		"/truenas/api/v2.0/activedirectory":                                      http.StatusUnauthorized,
		"/truenas/api/v2.0/activedirectory/change_trust_account_pw":              http.StatusUnauthorized,
		"/truenas/api/v2.0/activedirectory/get_spn_list":                         http.StatusUnauthorized,
		"/truenas/api/v2.0/activedirectory/get_state":                            http.StatusUnauthorized,
		"/truenas/api/v2.0/activedirectory/nss_info_choices":                     http.StatusUnauthorized,
		"/truenas/api/v2.0/activedirectory/started":                              http.StatusUnauthorized,
		"/truenas/api/v2.0/alert/list":                                           http.StatusUnauthorized,
		"/truenas/api/v2.0/alert/list_categories":                                http.StatusUnauthorized,
		"/truenas/api/v2.0/alert/list_policies":                                  http.StatusUnauthorized,
		"/truenas/api/v2.0/alertclasses":                                         http.StatusUnauthorized,
		"/truenas/api/v2.0/alertservice":                                         http.StatusUnauthorized,
		"/truenas/api/v2.0/alertservice/id/{id}":                                 http.StatusUnauthorized,
		"/truenas/api/v2.0/alertservice/list_types":                              http.StatusUnauthorized,
		"/truenas/api/v2.0/api_key":                                              http.StatusUnauthorized,
		"/truenas/api/v2.0/api_key/id/{id}":                                      http.StatusUnauthorized,
		"/truenas/api/v2.0/auth/two_factor_auth":                                 http.StatusUnauthorized,
		"/truenas/api/v2.0/auth/twofactor":                                       http.StatusUnauthorized,
		"/truenas/api/v2.0/auth/twofactor/provisioning_uri":                      http.StatusUnauthorized,
		"/truenas/api/v2.0/auth/twofactor/renew_secret":                          http.StatusUnauthorized,
		"/truenas/api/v2.0/boot/get_disks":                                       http.StatusUnauthorized,
		"/truenas/api/v2.0/boot/get_scrub_interval":                              http.StatusUnauthorized,
		"/truenas/api/v2.0/boot/get_state":                                       http.StatusUnauthorized,
		"/truenas/api/v2.0/boot/scrub":                                           http.StatusUnauthorized,
		"/truenas/api/v2.0/bootenv":                                              http.StatusUnauthorized,
		"/truenas/api/v2.0/bootenv/id/{id}":                                      http.StatusUnauthorized,
		"/truenas/api/v2.0/catalog":                                              http.StatusUnauthorized,
		"/truenas/api/v2.0/catalog/id/{id}":                                      http.StatusUnauthorized,
		"/truenas/api/v2.0/catalog/sync_all":                                     http.StatusUnauthorized,
		"/truenas/api/v2.0/certificate":                                          http.StatusUnauthorized,
		"/truenas/api/v2.0/certificate/id/{id}":                                  http.StatusUnauthorized,
		"/truenas/api/v2.0/certificate/acme_server_choices":                      http.StatusUnauthorized,
		"/truenas/api/v2.0/certificate/certificate_signing_requests_profiles":    http.StatusUnauthorized,
		"/truenas/api/v2.0/certificate/country_choices":                          http.StatusUnauthorized,
		"/truenas/api/v2.0/certificate/ec_curve_choices":                         http.StatusUnauthorized,
		"/truenas/api/v2.0/certificate/extended_key_usage_choices":               http.StatusUnauthorized,
		"/truenas/api/v2.0/certificate/key_type_choices":                         http.StatusUnauthorized,
		"/truenas/api/v2.0/certificate/profiles":                                 http.StatusUnauthorized,
		"/truenas/api/v2.0/certificateauthority":                                 http.StatusUnauthorized,
		"/truenas/api/v2.0/certificateauthority/id/{id}":                         http.StatusUnauthorized,
		"/truenas/api/v2.0/certificateauthority/profiles":                        http.StatusUnauthorized,
		"/truenas/api/v2.0/chart/release":                                        http.StatusUnauthorized,
		"/truenas/api/v2.0/chart/release/id/{id}":                                http.StatusUnauthorized,
		"/truenas/api/v2.0/chart/release/certificate_authority_choices":          http.StatusUnauthorized,
		"/truenas/api/v2.0/chart/release/certificate_choices":                    http.StatusUnauthorized,
		"/truenas/api/v2.0/chart/release/nic_choices":                            http.StatusUnauthorized,
		"/truenas/api/v2.0/chart/release/scaleable_resources":                    http.StatusUnauthorized,
		"/truenas/api/v2.0/chart/release/used_ports":                             http.StatusUnauthorized,
		"/truenas/api/v2.0/cloudsync":                                            http.StatusUnauthorized,
		"/truenas/api/v2.0/cloudsync/id/{id}":                                    http.StatusUnauthorized,
		"/truenas/api/v2.0/cloudsync/providers":                                  http.StatusUnauthorized,
		"/truenas/api/v2.0/cloudsync/credentials":                                http.StatusUnauthorized,
		"/truenas/api/v2.0/cloudsync/credentials/id/{id}":                        http.StatusUnauthorized,
		"/truenas/api/v2.0/container":                                            http.StatusUnauthorized,
		"/truenas/api/v2.0/container/image":                                      http.StatusUnauthorized,
		"/truenas/api/v2.0/container/image/id/{id}":                              http.StatusUnauthorized,
		"/truenas/api/v2.0/cronjob":                                              http.StatusUnauthorized,
		"/truenas/api/v2.0/cronjob/id/{id}":                                      http.StatusUnauthorized,
		"/truenas/api/v2.0/ctdb/general/healthy":                                 http.StatusUnauthorized,
		"/truenas/api/v2.0/ctdb/general/listnodes":                               http.StatusUnauthorized,
		"/truenas/api/v2.0/ctdb/general/pnn":                                     http.StatusUnauthorized,
		"/truenas/api/v2.0/ctdb/general/recovery_master":                         http.StatusUnauthorized,
		"/truenas/api/v2.0/ctdb/private/ips":                                     http.StatusUnauthorized,
		"/truenas/api/v2.0/ctdb/private/ips/id/{id}":                             http.StatusUnauthorized,
		"/truenas/api/v2.0/ctdb/public/ips":                                      http.StatusUnauthorized,
		"/truenas/api/v2.0/ctdb/public/ips/id/{id}":                              http.StatusUnauthorized,
		"/truenas/api/v2.0/device/gpu_pci_ids_choices":                           http.StatusUnauthorized,
		"/truenas/api/v2.0/directoryservices/cache_refresh":                      http.StatusUnauthorized,
		"/truenas/api/v2.0/directoryservices/get_state":                          http.StatusUnauthorized,
		"/truenas/api/v2.0/disk":                                                 http.StatusUnauthorized,
		"/truenas/api/v2.0/disk/id/{id}":                                         http.StatusUnauthorized,
		"/truenas/api/v2.0/dns/query":                                            http.StatusUnauthorized,
		"/truenas/api/v2.0/dyndns":                                               http.StatusUnauthorized,
		"/truenas/api/v2.0/dyndns/provider_choices":                              http.StatusUnauthorized,
		"/truenas/api/v2.0/enclosure":                                            http.StatusUnauthorized,
		"/truenas/api/v2.0/enclosure/id/{id}":                                    http.StatusUnauthorized,
		"/truenas/api/v2.0/failover":                                             http.StatusUnauthorized,
		"/truenas/api/v2.0/failover/become_passive":                              http.StatusUnauthorized,
		"/truenas/api/v2.0/failover/force_master":                                http.StatusUnauthorized,
		"/truenas/api/v2.0/failover/get_ips":                                     http.StatusUnauthorized,
		"/truenas/api/v2.0/failover/hardware":                                    http.StatusUnauthorized,
		"/truenas/api/v2.0/failover/in_progress":                                 http.StatusUnauthorized,
		"/truenas/api/v2.0/failover/licensed":                                    http.StatusUnauthorized,
		"/truenas/api/v2.0/failover/node":                                        http.StatusUnauthorized,
		"/truenas/api/v2.0/failover/status":                                      http.StatusUnauthorized,
		"/truenas/api/v2.0/failover/sync_from_peer":                              http.StatusUnauthorized,
		"/truenas/api/v2.0/failover/upgrade_finish":                              http.StatusUnauthorized,
		"/truenas/api/v2.0/failover/upgrade_pending":                             http.StatusUnauthorized,
		"/truenas/api/v2.0/filesystem/acltemplate":                               http.StatusUnauthorized,
		"/truenas/api/v2.0/filesystem/acltemplate/id/{id}":                       http.StatusUnauthorized,
		"/truenas/api/v2.0/ftp":                                                  http.StatusUnauthorized,
		"/truenas/api/v2.0/gluster/eventsd/sync":                                 http.StatusUnauthorized,
		"/truenas/api/v2.0/gluster/eventsd/webhooks":                             http.StatusUnauthorized,
		"/truenas/api/v2.0/gluster/localevents/get_set_jwt_secret":               http.StatusUnauthorized,
		"/truenas/api/v2.0/gluster/peer":                                         http.StatusUnauthorized,
		"/truenas/api/v2.0/gluster/peer/id/{id}":                                 http.StatusUnauthorized,
		"/truenas/api/v2.0/gluster/peer/ips_available":                           http.StatusUnauthorized,
		"/truenas/api/v2.0/gluster/volume":                                       http.StatusUnauthorized,
		"/truenas/api/v2.0/gluster/volume/id/{id}":                               http.StatusUnauthorized,
		"/truenas/api/v2.0/gluster/volume/list":                                  http.StatusUnauthorized,
		"/truenas/api/v2.0/group":                                                http.StatusUnauthorized,
		"/truenas/api/v2.0/group/id/{id}":                                        http.StatusUnauthorized,
		"/truenas/api/v2.0/group/get_next_gid":                                   http.StatusUnauthorized,
		"/truenas/api/v2.0/idmap":                                                http.StatusUnauthorized,
		"/truenas/api/v2.0/idmap/id/{id}":                                        http.StatusUnauthorized,
		"/truenas/api/v2.0/idmap/backend_choices":                                http.StatusUnauthorized,
		"/truenas/api/v2.0/idmap/backend_options":                                http.StatusUnauthorized,
		"/truenas/api/v2.0/idmap/clear_idmap_cache":                              http.StatusUnauthorized,
		"/truenas/api/v2.0/initshutdownscript":                                   http.StatusUnauthorized,
		"/truenas/api/v2.0/initshutdownscript/id/{id}":                           http.StatusUnauthorized,
		"/truenas/api/v2.0/interface":                                            http.StatusUnauthorized,
		"/truenas/api/v2.0/interface/id/{id}":                                    http.StatusUnauthorized,
		"/truenas/api/v2.0/interface/checkin":                                    http.StatusUnauthorized,
		"/truenas/api/v2.0/interface/checkin_waiting":                            http.StatusUnauthorized,
		"/truenas/api/v2.0/interface/has_pending_changes":                        http.StatusUnauthorized,
		"/truenas/api/v2.0/interface/lacpdu_rate_choices":                        http.StatusUnauthorized,
		"/truenas/api/v2.0/interface/rollback":                                   http.StatusUnauthorized,
		"/truenas/api/v2.0/interface/services_restarted_on_sync":                 http.StatusUnauthorized,
		"/truenas/api/v2.0/interface/vlan_parent_interface_choices":              http.StatusUnauthorized,
		"/truenas/api/v2.0/interface/xmit_hash_policy_choices":                   http.StatusUnauthorized,
		"/truenas/api/v2.0/ipmi":                                                 http.StatusUnauthorized,
		"/truenas/api/v2.0/ipmi/id/{id}":                                         http.StatusUnauthorized,
		"/truenas/api/v2.0/ipmi/channels":                                        http.StatusUnauthorized,
		"/truenas/api/v2.0/ipmi/clear_sel":                                       http.StatusUnauthorized,
		"/truenas/api/v2.0/ipmi/is_loaded":                                       http.StatusUnauthorized,
		"/truenas/api/v2.0/ipmi/query_sel":                                       http.StatusUnauthorized,
		"/truenas/api/v2.0/iscsi/auth":                                           http.StatusUnauthorized,
		"/truenas/api/v2.0/iscsi/auth/id/{id}":                                   http.StatusUnauthorized,
		"/truenas/api/v2.0/iscsi/extent":                                         http.StatusUnauthorized,
		"/truenas/api/v2.0/iscsi/extent/id/{id}":                                 http.StatusUnauthorized,
		"/truenas/api/v2.0/iscsi/extent/disk_choices":                            http.StatusUnauthorized,
		"/truenas/api/v2.0/iscsi/global":                                         http.StatusUnauthorized,
		"/truenas/api/v2.0/iscsi/global/alua_enabled":                            http.StatusUnauthorized,
		"/truenas/api/v2.0/iscsi/global/client_count":                            http.StatusUnauthorized,
		"/truenas/api/v2.0/iscsi/global/sessions":                                http.StatusUnauthorized,
		"/truenas/api/v2.0/iscsi/host":                                           http.StatusUnauthorized,
		"/truenas/api/v2.0/iscsi/host/id/{id}":                                   http.StatusUnauthorized,
		"/truenas/api/v2.0/iscsi/initiator":                                      http.StatusUnauthorized,
		"/truenas/api/v2.0/iscsi/initiator/id/{id}":                              http.StatusUnauthorized,
		"/truenas/api/v2.0/iscsi/portal":                                         http.StatusUnauthorized,
		"/truenas/api/v2.0/iscsi/portal/id/{id}":                                 http.StatusUnauthorized,
		"/truenas/api/v2.0/iscsi/portal/listen_ip_choices":                       http.StatusUnauthorized,
		"/truenas/api/v2.0/iscsi/target":                                         http.StatusUnauthorized,
		"/truenas/api/v2.0/iscsi/target/id/{id}":                                 http.StatusUnauthorized,
		"/truenas/api/v2.0/iscsi/targetextent":                                   http.StatusUnauthorized,
		"/truenas/api/v2.0/iscsi/targetextent/id/{id}":                           http.StatusUnauthorized,
		"/truenas/api/v2.0/kerberos":                                             http.StatusUnauthorized,
		"/truenas/api/v2.0/kerberos/keytab":                                      http.StatusUnauthorized,
		"/truenas/api/v2.0/kerberos/keytab/id/{id}":                              http.StatusUnauthorized,
		"/truenas/api/v2.0/kerberos/keytab/system_keytab_list":                   http.StatusUnauthorized,
		"/truenas/api/v2.0/kerberos/realm":                                       http.StatusUnauthorized,
		"/truenas/api/v2.0/kerberos/realm/id/{id}":                               http.StatusUnauthorized,
		"/truenas/api/v2.0/keychaincredential":                                   http.StatusUnauthorized,
		"/truenas/api/v2.0/keychaincredential/id/{id}":                           http.StatusUnauthorized,
		"/truenas/api/v2.0/keychaincredential/generate_ssh_key_pair":             http.StatusUnauthorized,
		"/truenas/api/v2.0/kmip":                                                 http.StatusUnauthorized,
		"/truenas/api/v2.0/kmip/clear_sync_pending_keys":                         http.StatusUnauthorized,
		"/truenas/api/v2.0/kmip/kmip_sync_pending":                               http.StatusUnauthorized,
		"/truenas/api/v2.0/kmip/ssl_version_choices":                             http.StatusUnauthorized,
		"/truenas/api/v2.0/kmip/sync_keys":                                       http.StatusUnauthorized,
		"/truenas/api/v2.0/kubernetes":                                           http.StatusUnauthorized,
		"/truenas/api/v2.0/kubernetes/bindip_choices":                            http.StatusUnauthorized,
		"/truenas/api/v2.0/kubernetes/events":                                    http.StatusUnauthorized,
		"/truenas/api/v2.0/kubernetes/list_backups":                              http.StatusUnauthorized,
		"/truenas/api/v2.0/kubernetes/node_ip":                                   http.StatusUnauthorized,
		"/truenas/api/v2.0/kubernetes/route_interface_choices":                   http.StatusUnauthorized,
		"/truenas/api/v2.0/ldap":                                                 http.StatusUnauthorized,
		"/truenas/api/v2.0/ldap/get_state":                                       http.StatusUnauthorized,
		"/truenas/api/v2.0/ldap/schema_choices":                                  http.StatusUnauthorized,
		"/truenas/api/v2.0/ldap/ssl_choices":                                     http.StatusUnauthorized,
		"/truenas/api/v2.0/lldp":                                                 http.StatusUnauthorized,
		"/truenas/api/v2.0/lldp/country_choices":                                 http.StatusUnauthorized,
		"/truenas/api/v2.0/mail":                                                 http.StatusUnauthorized,
		"/truenas/api/v2.0/network/configuration":                                http.StatusUnauthorized,
		"/truenas/api/v2.0/network/configuration/activity_choices":               http.StatusUnauthorized,
		"/truenas/api/v2.0/network/general/summary":                              http.StatusUnauthorized,
		"/truenas/api/v2.0/nfs":                                                  http.StatusUnauthorized,
		"/truenas/api/v2.0/nfs/bindip_choices":                                   http.StatusUnauthorized,
		"/truenas/api/v2.0/nfs/client_count":                                     http.StatusUnauthorized,
		"/truenas/api/v2.0/nfs/get_nfs3_clients":                                 http.StatusUnauthorized,
		"/truenas/api/v2.0/nfs/get_nfs4_clients":                                 http.StatusUnauthorized,
		"/truenas/api/v2.0/openvpn/client":                                       http.StatusUnauthorized,
		"/truenas/api/v2.0/openvpn/client/authentication_algorithm_choices":      http.StatusUnauthorized,
		"/truenas/api/v2.0/openvpn/client/cipher_choices":                        http.StatusUnauthorized,
		"/truenas/api/v2.0/openvpn/server":                                       http.StatusUnauthorized,
		"/truenas/api/v2.0/openvpn/server/authentication_algorithm_choices":      http.StatusUnauthorized,
		"/truenas/api/v2.0/openvpn/server/cipher_choices":                        http.StatusUnauthorized,
		"/truenas/api/v2.0/openvpn/server/renew_static_key":                      http.StatusUnauthorized,
		"/truenas/api/v2.0/pool":                                                 http.StatusOK,
		"/truenas/api/v2.0/pool/id/{id}":                                         http.StatusUnauthorized,
		"/truenas/api/v2.0/pool/import_disk_msdosfs_locales":                     http.StatusUnauthorized,
		"/truenas/api/v2.0/pool/import_find":                                     http.StatusUnauthorized,
		"/truenas/api/v2.0/pool/dataset":                                         http.StatusOK,
		"/truenas/api/v2.0/pool/dataset/id/{id}":                                 http.StatusUnauthorized,
		"/truenas/api/v2.0/pool/dataset/checksum_choices":                        http.StatusUnauthorized,
		"/truenas/api/v2.0/pool/dataset/compression_choices":                     http.StatusUnauthorized,
		"/truenas/api/v2.0/pool/dataset/encryption_algorithm_choices":            http.StatusUnauthorized,
		"/truenas/api/v2.0/pool/dataset/recordsize_choices":                      http.StatusUnauthorized,
		"/truenas/api/v2.0/pool/dataset/userprop":                                http.StatusUnauthorized,
		"/truenas/api/v2.0/pool/dataset/userprop/id/{id}":                        http.StatusUnauthorized,
		"/truenas/api/v2.0/pool/resilver":                                        http.StatusUnauthorized,
		"/truenas/api/v2.0/pool/scrub":                                           http.StatusUnauthorized,
		"/truenas/api/v2.0/pool/scrub/id/{id}":                                   http.StatusUnauthorized,
		"/truenas/api/v2.0/pool/snapshottask":                                    http.StatusUnauthorized,
		"/truenas/api/v2.0/pool/snapshottask/id/{id}":                            http.StatusUnauthorized,
		"/truenas/api/v2.0/pool/snapshottask/max_count":                          http.StatusUnauthorized,
		"/truenas/api/v2.0/pool/snapshottask/max_total_count":                    http.StatusUnauthorized,
		"/truenas/api/v2.0/replication":                                          http.StatusUnauthorized,
		"/truenas/api/v2.0/replication/id/{id}":                                  http.StatusUnauthorized,
		"/truenas/api/v2.0/replication/list_naming_schemas":                      http.StatusUnauthorized,
		"/truenas/api/v2.0/replication/config":                                   http.StatusUnauthorized,
		"/truenas/api/v2.0/reporting":                                            http.StatusUnauthorized,
		"/truenas/api/v2.0/reporting/clear":                                      http.StatusUnauthorized,
		"/truenas/api/v2.0/reporting/graphs":                                     http.StatusUnauthorized,
		"/truenas/api/v2.0/route/system_routes":                                  http.StatusUnauthorized,
		"/truenas/api/v2.0/rsyncd":                                               http.StatusUnauthorized,
		"/truenas/api/v2.0/rsyncmod":                                             http.StatusUnauthorized,
		"/truenas/api/v2.0/rsyncmod/id/{id}":                                     http.StatusUnauthorized,
		"/truenas/api/v2.0/rsynctask":                                            http.StatusUnauthorized,
		"/truenas/api/v2.0/rsynctask/id/{id}":                                    http.StatusUnauthorized,
		"/truenas/api/v2.0/s3":                                                   http.StatusUnauthorized,
		"/truenas/api/v2.0/s3/bindip_choices":                                    http.StatusUnauthorized,
		"/truenas/api/v2.0/sensor/query":                                         http.StatusUnauthorized,
		"/truenas/api/v2.0/service":                                              http.StatusUnauthorized,
		"/truenas/api/v2.0/service/id/{id}":                                      http.StatusUnauthorized,
		"/truenas/api/v2.0/sharing/nfs":                                          http.StatusUnauthorized,
		"/truenas/api/v2.0/sharing/nfs/id/{id}":                                  http.StatusUnauthorized,
		"/truenas/api/v2.0/sharing/smb":                                          http.StatusUnauthorized,
		"/truenas/api/v2.0/sharing/smb/id/{id}":                                  http.StatusUnauthorized,
		"/truenas/api/v2.0/sharing/smb/presets":                                  http.StatusUnauthorized,
		"/truenas/api/v2.0/sharing/webdav":                                       http.StatusUnauthorized,
		"/truenas/api/v2.0/sharing/webdav/id/{id}":                               http.StatusUnauthorized,
		"/truenas/api/v2.0/smart":                                                http.StatusUnauthorized,
		"/truenas/api/v2.0/smart/test":                                           http.StatusUnauthorized,
		"/truenas/api/v2.0/smart/test/id/{id}":                                   http.StatusUnauthorized,
		"/truenas/api/v2.0/smart/test/results":                                   http.StatusUnauthorized,
		"/truenas/api/v2.0/smb":                                                  http.StatusUnauthorized,
		"/truenas/api/v2.0/smb/bindip_choices":                                   http.StatusUnauthorized,
		"/truenas/api/v2.0/smb/client_count":                                     http.StatusUnauthorized,
		"/truenas/api/v2.0/smb/domain_choices":                                   http.StatusUnauthorized,
		"/truenas/api/v2.0/smb/unixcharset_choices":                              http.StatusUnauthorized,
		"/truenas/api/v2.0/smb/sharesec":                                         http.StatusUnauthorized,
		"/truenas/api/v2.0/smb/sharesec/id/{id}":                                 http.StatusUnauthorized,
		"/truenas/api/v2.0/smb/sharesec/synchronize_acls":                        http.StatusUnauthorized,
		"/truenas/api/v2.0/snmp":                                                 http.StatusUnauthorized,
		"/truenas/api/v2.0/ssh":                                                  http.StatusUnauthorized,
		"/truenas/api/v2.0/ssh/bindiface_choices":                                http.StatusUnauthorized,
		"/truenas/api/v2.0/staticroute":                                          http.StatusUnauthorized,
		"/truenas/api/v2.0/staticroute/id/{id}":                                  http.StatusUnauthorized,
		"/truenas/api/v2.0/stats/get_sources":                                    http.StatusUnauthorized,
		"/truenas/api/v2.0/support":                                              http.StatusUnauthorized,
		"/truenas/api/v2.0/support/attach_ticket_max_size":                       http.StatusUnauthorized,
		"/truenas/api/v2.0/support/fields":                                       http.StatusUnauthorized,
		"/truenas/api/v2.0/support/is_available":                                 http.StatusUnauthorized,
		"/truenas/api/v2.0/support/is_available_and_enabled":                     http.StatusUnauthorized,
		"/truenas/api/v2.0/system/boot_id":                                       http.StatusUnauthorized,
		"/truenas/api/v2.0/system/debug":                                         http.StatusUnauthorized,
		"/truenas/api/v2.0/system/environment":                                   http.StatusUnauthorized,
		"/truenas/api/v2.0/system/host_id":                                       http.StatusUnauthorized,
		"/truenas/api/v2.0/system/info":                                          http.StatusUnauthorized,
		"/truenas/api/v2.0/system/is_freenas":                                    http.StatusUnauthorized,
		"/truenas/api/v2.0/system/is_stable":                                     http.StatusUnauthorized,
		"/truenas/api/v2.0/system/product_name":                                  http.StatusUnauthorized,
		"/truenas/api/v2.0/system/product_type":                                  http.StatusUnauthorized,
		"/truenas/api/v2.0/system/ready":                                         http.StatusUnauthorized,
		"/truenas/api/v2.0/system/state":                                         http.StatusUnauthorized,
		"/truenas/api/v2.0/system/version":                                       http.StatusUnauthorized,
		"/truenas/api/v2.0/system/advanced":                                      http.StatusUnauthorized,
		"/truenas/api/v2.0/system/advanced/sed_global_password":                  http.StatusUnauthorized,
		"/truenas/api/v2.0/system/advanced/serial_port_choices":                  http.StatusUnauthorized,
		"/truenas/api/v2.0/system/advanced/syslog_certificate_authority_choices": http.StatusUnauthorized,
		"/truenas/api/v2.0/system/advanced/syslog_certificate_choices":           http.StatusUnauthorized,
		"/truenas/api/v2.0/system/general":                                       http.StatusUnauthorized,
		"/truenas/api/v2.0/system/general/country_choices":                       http.StatusUnauthorized,
		"/truenas/api/v2.0/system/general/kbdmap_choices":                        http.StatusUnauthorized,
		"/truenas/api/v2.0/system/general/language_choices":                      http.StatusUnauthorized,
		"/truenas/api/v2.0/system/general/local_url":                             http.StatusUnauthorized,
		"/truenas/api/v2.0/system/general/timezone_choices":                      http.StatusUnauthorized,
		"/truenas/api/v2.0/system/general/ui_address_choices":                    http.StatusUnauthorized,
		"/truenas/api/v2.0/system/general/ui_certificate_choices":                http.StatusUnauthorized,
		"/truenas/api/v2.0/system/general/ui_httpsprotocols_choices":             http.StatusUnauthorized,
		"/truenas/api/v2.0/system/general/ui_restart":                            http.StatusUnauthorized,
		"/truenas/api/v2.0/system/general/ui_v6address_choices":                  http.StatusUnauthorized,
		"/truenas/api/v2.0/system/ntpserver":                                     http.StatusUnauthorized,
		"/truenas/api/v2.0/system/ntpserver/id/{id}":                             http.StatusUnauthorized,
		"/truenas/api/v2.0/systemdataset":                                        http.StatusUnauthorized,
		"/truenas/api/v2.0/systemdataset/pool_choices":                           http.StatusUnauthorized,
		"/truenas/api/v2.0/tftp":                                                 http.StatusUnauthorized,
		"/truenas/api/v2.0/tftp/host_choices":                                    http.StatusUnauthorized,
		"/truenas/api/v2.0/truecommand":                                          http.StatusUnauthorized,
		"/truenas/api/v2.0/truenas/accept_eula":                                  http.StatusUnauthorized,
		"/truenas/api/v2.0/truenas/get_chassis_hardware":                         http.StatusUnauthorized,
		"/truenas/api/v2.0/truenas/get_customer_information":                     http.StatusUnauthorized,
		"/truenas/api/v2.0/truenas/get_eula":                                     http.StatusUnauthorized,
		"/truenas/api/v2.0/truenas/is_eula_accepted":                             http.StatusUnauthorized,
		"/truenas/api/v2.0/truenas/is_production":                                http.StatusUnauthorized,
		"/truenas/api/v2.0/tunable":                                              http.StatusUnauthorized,
		"/truenas/api/v2.0/tunable/id/{id}":                                      http.StatusUnauthorized,
		"/truenas/api/v2.0/tunable/tunable_type_choices":                         http.StatusUnauthorized,
		"/truenas/api/v2.0/update/download":                                      http.StatusUnauthorized,
		"/truenas/api/v2.0/update/get_auto_download":                             http.StatusUnauthorized,
		"/truenas/api/v2.0/update/get_trains":                                    http.StatusUnauthorized,
		"/truenas/api/v2.0/ups":                                                  http.StatusUnauthorized,
		"/truenas/api/v2.0/ups/driver_choices":                                   http.StatusUnauthorized,
		"/truenas/api/v2.0/ups/port_choices":                                     http.StatusUnauthorized,
		"/truenas/api/v2.0/user":                                                 http.StatusUnauthorized,
		"/truenas/api/v2.0/user/id/{id}":                                         http.StatusUnauthorized,
		"/truenas/api/v2.0/user/get_next_uid":                                    http.StatusUnauthorized,
		"/truenas/api/v2.0/user/has_root_password":                               http.StatusUnauthorized,
		"/truenas/api/v2.0/vm":                                                   http.StatusUnauthorized,
		"/truenas/api/v2.0/vm/id/{id}":                                           http.StatusUnauthorized,
		"/truenas/api/v2.0/vm/bootloader_options":                                http.StatusUnauthorized,
		"/truenas/api/v2.0/vm/cpu_model_choices":                                 http.StatusUnauthorized,
		"/truenas/api/v2.0/vm/flags":                                             http.StatusUnauthorized,
		"/truenas/api/v2.0/vm/get_vmemory_in_use":                                http.StatusUnauthorized,
		"/truenas/api/v2.0/vm/guest_architecture_and_machine_choices":            http.StatusUnauthorized,
		"/truenas/api/v2.0/vm/maximum_supported_vcpus":                           http.StatusUnauthorized,
		"/truenas/api/v2.0/vm/port_wizard":                                       http.StatusUnauthorized,
		"/truenas/api/v2.0/vm/random_mac":                                        http.StatusUnauthorized,
		"/truenas/api/v2.0/vm/resolution_choices":                                http.StatusUnauthorized,
		"/truenas/api/v2.0/vm/supports_virtualization":                           http.StatusUnauthorized,
		"/truenas/api/v2.0/vm/virtualization_details":                            http.StatusUnauthorized,
		"/truenas/api/v2.0/vm/device":                                            http.StatusUnauthorized,
		"/truenas/api/v2.0/vm/device/id/{id}":                                    http.StatusUnauthorized,
		"/truenas/api/v2.0/vm/device/bind_choices":                               http.StatusUnauthorized,
		"/truenas/api/v2.0/vm/device/disk_choices":                               http.StatusUnauthorized,
		"/truenas/api/v2.0/vm/device/iommu_enabled":                              http.StatusUnauthorized,
		"/truenas/api/v2.0/vm/device/nic_attach_choices":                         http.StatusUnauthorized,
		"/truenas/api/v2.0/vm/device/passthrough_device_choices":                 http.StatusUnauthorized,
		"/truenas/api/v2.0/vm/device/pptdev_choices":                             http.StatusUnauthorized,
		"/truenas/api/v2.0/vmware":                                               http.StatusUnauthorized,
		"/truenas/api/v2.0/vmware/id/{id}":                                       http.StatusUnauthorized,
		"/truenas/api/v2.0/webdav":                                               http.StatusUnauthorized,
		"/truenas/api/v2.0/webdav/cert_choices":                                  http.StatusUnauthorized,
		"/truenas/api/v2.0/webui/image":                                          http.StatusUnauthorized,
		"/truenas/api/v2.0/webui/image/id/{id}":                                  http.StatusUnauthorized,
		"/truenas/api/v2.0/zfs/snapshot":                                         http.StatusUnauthorized,
		"/truenas/api/v2.0/zfs/snapshot/id/{id}":                                 http.StatusUnauthorized,
	},
	http.MethodPost: {
		"/truenas/api/v2.0/core/bulk":                                                  http.StatusUnauthorized,
		"/truenas/api/v2.0/core/debug":                                                 http.StatusUnauthorized,
		"/truenas/api/v2.0/core/download":                                              http.StatusUnauthorized,
		"/truenas/api/v2.0/core/job_abort":                                             http.StatusUnauthorized,
		"/truenas/api/v2.0/core/job_update":                                            http.StatusUnauthorized,
		"/truenas/api/v2.0/core/job_wait":                                              http.StatusUnauthorized,
		"/truenas/api/v2.0/core/ping_remote":                                           http.StatusUnauthorized,
		"/truenas/api/v2.0/core/resize_shell":                                          http.StatusUnauthorized,
		"/truenas/api/v2.0/core/set_debug_mode":                                        http.StatusUnauthorized,
		"/truenas/api/v2.0/acme/dns/authenticator":                                     http.StatusUnauthorized,
		"/truenas/api/v2.0/activedirectory/domain_info":                                http.StatusUnauthorized,
		"/truenas/api/v2.0/activedirectory/leave":                                      http.StatusUnauthorized,
		"/truenas/api/v2.0/alert/dismiss":                                              http.StatusUnauthorized,
		"/truenas/api/v2.0/alert/restore":                                              http.StatusUnauthorized,
		"/truenas/api/v2.0/alertservice":                                               http.StatusUnauthorized,
		"/truenas/api/v2.0/alertservice/test":                                          http.StatusUnauthorized,
		"/truenas/api/v2.0/api_key":                                                    http.StatusUnauthorized,
		"/truenas/api/v2.0/auth/check_password":                                        http.StatusUnauthorized,
		"/truenas/api/v2.0/auth/check_user":                                            http.StatusUnauthorized,
		"/truenas/api/v2.0/auth/generate_token":                                        http.StatusUnauthorized,
		"/truenas/api/v2.0/auth/twofactor/verify":                                      http.StatusUnauthorized,
		"/truenas/api/v2.0/boot/attach":                                                http.StatusUnauthorized,
		"/truenas/api/v2.0/boot/detach":                                                http.StatusUnauthorized,
		"/truenas/api/v2.0/boot/replace":                                               http.StatusUnauthorized,
		"/truenas/api/v2.0/boot/set_scrub_interval":                                    http.StatusUnauthorized,
		"/truenas/api/v2.0/bootenv":                                                    http.StatusUnauthorized,
		"/truenas/api/v2.0/bootenv/id/{id}/activate":                                   http.StatusUnauthorized,
		"/truenas/api/v2.0/bootenv/id/{id}/set_attribute":                              http.StatusUnauthorized,
		"/truenas/api/v2.0/catalog":                                                    http.StatusUnauthorized,
		"/truenas/api/v2.0/catalog/get_item_details":                                   http.StatusUnauthorized,
		"/truenas/api/v2.0/catalog/items":                                              http.StatusUnauthorized,
		"/truenas/api/v2.0/catalog/sync":                                               http.StatusUnauthorized,
		"/truenas/api/v2.0/catalog/validate":                                           http.StatusUnauthorized,
		"/truenas/api/v2.0/certificate":                                                http.StatusUnauthorized,
		"/truenas/api/v2.0/certificateauthority":                                       http.StatusUnauthorized,
		"/truenas/api/v2.0/certificateauthority/ca_sign_csr":                           http.StatusUnauthorized,
		"/truenas/api/v2.0/chart/release":                                              http.StatusUnauthorized,
		"/truenas/api/v2.0/chart/release/events":                                       http.StatusUnauthorized,
		"/truenas/api/v2.0/chart/release/pod_console_choices":                          http.StatusUnauthorized,
		"/truenas/api/v2.0/chart/release/pod_logs":                                     http.StatusUnauthorized,
		"/truenas/api/v2.0/chart/release/pod_logs_choices":                             http.StatusUnauthorized,
		"/truenas/api/v2.0/chart/release/pod_status":                                   http.StatusUnauthorized,
		"/truenas/api/v2.0/chart/release/pull_container_images":                        http.StatusUnauthorized,
		"/truenas/api/v2.0/chart/release/redeploy":                                     http.StatusUnauthorized,
		"/truenas/api/v2.0/chart/release/remove_ix_volume":                             http.StatusUnauthorized,
		"/truenas/api/v2.0/chart/release/rollback":                                     http.StatusUnauthorized,
		"/truenas/api/v2.0/chart/release/scale":                                        http.StatusUnauthorized,
		"/truenas/api/v2.0/chart/release/scale_workloads":                              http.StatusUnauthorized,
		"/truenas/api/v2.0/chart/release/upgrade":                                      http.StatusUnauthorized,
		"/truenas/api/v2.0/chart/release/upgrade_summary":                              http.StatusUnauthorized,
		"/truenas/api/v2.0/cloudsync":                                                  http.StatusUnauthorized,
		"/truenas/api/v2.0/cloudsync/id/{id}/abort":                                    http.StatusUnauthorized,
		"/truenas/api/v2.0/cloudsync/list_buckets":                                     http.StatusUnauthorized,
		"/truenas/api/v2.0/cloudsync/list_directory":                                   http.StatusUnauthorized,
		"/truenas/api/v2.0/cloudsync/onedrive_list_drives":                             http.StatusUnauthorized,
		"/truenas/api/v2.0/cloudsync/id/{id}/restore":                                  http.StatusUnauthorized,
		"/truenas/api/v2.0/cloudsync/id/{id}/sync":                                     http.StatusUnauthorized,
		"/truenas/api/v2.0/cloudsync/sync_onetime":                                     http.StatusUnauthorized,
		"/truenas/api/v2.0/cloudsync/credentials":                                      http.StatusUnauthorized,
		"/truenas/api/v2.0/cloudsync/credentials/verify":                               http.StatusUnauthorized,
		"/truenas/api/v2.0/config/reset":                                               http.StatusUnauthorized,
		"/truenas/api/v2.0/config/save":                                                http.StatusUnauthorized,
		"/truenas/api/v2.0/config/upload":                                              http.StatusUnauthorized,
		"/truenas/api/v2.0/container/prune":                                            http.StatusUnauthorized,
		"/truenas/api/v2.0/container/image/pull":                                       http.StatusUnauthorized,
		"/truenas/api/v2.0/cronjob":                                                    http.StatusUnauthorized,
		"/truenas/api/v2.0/cronjob/run":                                                http.StatusUnauthorized,
		"/truenas/api/v2.0/ctdb/general/ips":                                           http.StatusUnauthorized,
		"/truenas/api/v2.0/ctdb/general/status":                                        http.StatusUnauthorized,
		"/truenas/api/v2.0/ctdb/private/ips":                                           http.StatusUnauthorized,
		"/truenas/api/v2.0/ctdb/public/ips":                                            http.StatusUnauthorized,
		"/truenas/api/v2.0/ctdb/public/ips/interface_choices":                          http.StatusUnauthorized,
		"/truenas/api/v2.0/device/get_info":                                            http.StatusUnauthorized,
		"/truenas/api/v2.0/disk/get_unused":                                            http.StatusUnauthorized,
		"/truenas/api/v2.0/disk/smart_attributes":                                      http.StatusUnauthorized,
		"/truenas/api/v2.0/disk/temperature":                                           http.StatusUnauthorized,
		"/truenas/api/v2.0/disk/temperatures":                                          http.StatusUnauthorized,
		"/truenas/api/v2.0/disk/wipe":                                                  http.StatusUnauthorized,
		"/truenas/api/v2.0/enclosure/set_slot_status":                                  http.StatusUnauthorized,
		"/truenas/api/v2.0/failover/call_remote":                                       http.StatusUnauthorized,
		"/truenas/api/v2.0/failover/control":                                           http.StatusUnauthorized,
		"/truenas/api/v2.0/failover/sync_to_peer":                                      http.StatusUnauthorized,
		"/truenas/api/v2.0/failover/unlock":                                            http.StatusUnauthorized,
		"/truenas/api/v2.0/failover/upgrade":                                           http.StatusUnauthorized,
		"/truenas/api/v2.0/filesystem/acl_is_trivial":                                  http.StatusUnauthorized,
		"/truenas/api/v2.0/filesystem/can_access_as_user":                              http.StatusUnauthorized,
		"/truenas/api/v2.0/filesystem/chown":                                           http.StatusUnauthorized,
		"/truenas/api/v2.0/filesystem/default_acl_choices":                             http.StatusUnauthorized,
		"/truenas/api/v2.0/filesystem/get":                                             http.StatusUnauthorized,
		"/truenas/api/v2.0/filesystem/get_default_acl":                                 http.StatusUnauthorized,
		"/truenas/api/v2.0/filesystem/get_dosmode":                                     http.StatusUnauthorized,
		"/truenas/api/v2.0/filesystem/getacl":                                          http.StatusUnauthorized,
		"/truenas/api/v2.0/filesystem/is_immutable":                                    http.StatusUnauthorized,
		"/truenas/api/v2.0/filesystem/listdir":                                         http.StatusOK,
		"/truenas/api/v2.0/filesystem/mkdir":                                           http.StatusUnauthorized,
		"/truenas/api/v2.0/filesystem/put":                                             http.StatusUnauthorized,
		"/truenas/api/v2.0/filesystem/set_dosmode":                                     http.StatusUnauthorized,
		"/truenas/api/v2.0/filesystem/set_immutable":                                   http.StatusUnauthorized,
		"/truenas/api/v2.0/filesystem/setacl":                                          http.StatusUnauthorized,
		"/truenas/api/v2.0/filesystem/setperm":                                         http.StatusUnauthorized,
		"/truenas/api/v2.0/filesystem/stat":                                            http.StatusUnauthorized,
		"/truenas/api/v2.0/filesystem/statfs":                                          http.StatusUnauthorized,
		"/truenas/api/v2.0/filesystem/acltemplate":                                     http.StatusUnauthorized,
		"/truenas/api/v2.0/filesystem/acltemplate/by_path":                             http.StatusUnauthorized,
		"/truenas/api/v2.0/gluster/eventsd/create":                                     http.StatusUnauthorized,
		"/truenas/api/v2.0/gluster/eventsd/delete":                                     http.StatusUnauthorized,
		"/truenas/api/v2.0/gluster/fuse/is_mounted":                                    http.StatusUnauthorized,
		"/truenas/api/v2.0/gluster/fuse/mount":                                         http.StatusUnauthorized,
		"/truenas/api/v2.0/gluster/fuse/umount":                                        http.StatusUnauthorized,
		"/truenas/api/v2.0/gluster/localevents/add_jwt_secret":                         http.StatusUnauthorized,
		"/truenas/api/v2.0/gluster/peer":                                               http.StatusUnauthorized,
		"/truenas/api/v2.0/gluster/peer/status":                                        http.StatusUnauthorized,
		"/truenas/api/v2.0/gluster/rebalance/fix_layout":                               http.StatusUnauthorized,
		"/truenas/api/v2.0/gluster/rebalance/start":                                    http.StatusUnauthorized,
		"/truenas/api/v2.0/gluster/rebalance/status":                                   http.StatusUnauthorized,
		"/truenas/api/v2.0/gluster/rebalance/stop":                                     http.StatusUnauthorized,
		"/truenas/api/v2.0/gluster/volume":                                             http.StatusUnauthorized,
		"/truenas/api/v2.0/gluster/volume/addbrick":                                    http.StatusUnauthorized,
		"/truenas/api/v2.0/gluster/volume/info":                                        http.StatusUnauthorized,
		"/truenas/api/v2.0/gluster/volume/optreset":                                    http.StatusUnauthorized,
		"/truenas/api/v2.0/gluster/volume/optset":                                      http.StatusUnauthorized,
		"/truenas/api/v2.0/gluster/volume/quota":                                       http.StatusUnauthorized,
		"/truenas/api/v2.0/gluster/volume/removebrick":                                 http.StatusUnauthorized,
		"/truenas/api/v2.0/gluster/volume/replacebrick":                                http.StatusUnauthorized,
		"/truenas/api/v2.0/gluster/volume/restart":                                     http.StatusUnauthorized,
		"/truenas/api/v2.0/gluster/volume/start":                                       http.StatusUnauthorized,
		"/truenas/api/v2.0/gluster/volume/status":                                      http.StatusUnauthorized,
		"/truenas/api/v2.0/gluster/volume/stop":                                        http.StatusUnauthorized,
		"/truenas/api/v2.0/group":                                                      http.StatusUnauthorized,
		"/truenas/api/v2.0/group/get_group_obj":                                        http.StatusUnauthorized,
		"/truenas/api/v2.0/idmap":                                                      http.StatusUnauthorized,
		"/truenas/api/v2.0/idmap/options_choices":                                      http.StatusUnauthorized,
		"/truenas/api/v2.0/initshutdownscript":                                         http.StatusUnauthorized,
		"/truenas/api/v2.0/interface":                                                  http.StatusUnauthorized,
		"/truenas/api/v2.0/interface/bridge_members_choices":                           http.StatusUnauthorized,
		"/truenas/api/v2.0/interface/choices":                                          http.StatusUnauthorized,
		"/truenas/api/v2.0/interface/commit":                                           http.StatusUnauthorized,
		"/truenas/api/v2.0/interface/ip_in_use":                                        http.StatusUnauthorized,
		"/truenas/api/v2.0/interface/lag_ports_choices":                                http.StatusUnauthorized,
		"/truenas/api/v2.0/interface/capabilities/get":                                 http.StatusUnauthorized,
		"/truenas/api/v2.0/interface/capabilities/set":                                 http.StatusUnauthorized,
		"/truenas/api/v2.0/ipmi/identify":                                              http.StatusUnauthorized,
		"/truenas/api/v2.0/iscsi/auth":                                                 http.StatusUnauthorized,
		"/truenas/api/v2.0/iscsi/extent":                                               http.StatusUnauthorized,
		"/truenas/api/v2.0/iscsi/host":                                                 http.StatusUnauthorized,
		"/truenas/api/v2.0/iscsi/host/get_initiators":                                  http.StatusUnauthorized,
		"/truenas/api/v2.0/iscsi/host/get_targets":                                     http.StatusUnauthorized,
		"/truenas/api/v2.0/iscsi/host/set_initiators":                                  http.StatusUnauthorized,
		"/truenas/api/v2.0/iscsi/host/set_targets":                                     http.StatusUnauthorized,
		"/truenas/api/v2.0/iscsi/initiator":                                            http.StatusUnauthorized,
		"/truenas/api/v2.0/iscsi/portal":                                               http.StatusUnauthorized,
		"/truenas/api/v2.0/iscsi/target":                                               http.StatusUnauthorized,
		"/truenas/api/v2.0/iscsi/targetextent":                                         http.StatusUnauthorized,
		"/truenas/api/v2.0/kerberos/keytab":                                            http.StatusUnauthorized,
		"/truenas/api/v2.0/kerberos/keytab/upload_keytab":                              http.StatusUnauthorized,
		"/truenas/api/v2.0/kerberos/realm":                                             http.StatusUnauthorized,
		"/truenas/api/v2.0/keychaincredential":                                         http.StatusUnauthorized,
		"/truenas/api/v2.0/keychaincredential/remote_ssh_host_key_scan":                http.StatusUnauthorized,
		"/truenas/api/v2.0/keychaincredential/remote_ssh_semiautomatic_setup":          http.StatusUnauthorized,
		"/truenas/api/v2.0/keychaincredential/setup_ssh_connection":                    http.StatusUnauthorized,
		"/truenas/api/v2.0/keychaincredential/used_by":                                 http.StatusUnauthorized,
		"/truenas/api/v2.0/kubernetes/backup_chart_releases":                           http.StatusUnauthorized,
		"/truenas/api/v2.0/kubernetes/delete_backup":                                   http.StatusUnauthorized,
		"/truenas/api/v2.0/kubernetes/restore_backup":                                  http.StatusUnauthorized,
		"/truenas/api/v2.0/mail/send":                                                  http.StatusUnauthorized,
		"/truenas/api/v2.0/nfs/add_principal":                                          http.StatusUnauthorized,
		"/truenas/api/v2.0/openvpn/server/client_configuration_generation":             http.StatusUnauthorized,
		"/truenas/api/v2.0/pool":                                                       http.StatusUnauthorized,
		"/truenas/api/v2.0/pool/attach":                                                http.StatusUnauthorized,
		"/truenas/api/v2.0/pool/id/{id}/attachments":                                   http.StatusUnauthorized,
		"/truenas/api/v2.0/pool/id/{id}/detach":                                        http.StatusUnauthorized,
		"/truenas/api/v2.0/pool/id/{id}/expand":                                        http.StatusUnauthorized,
		"/truenas/api/v2.0/pool/id/{id}/export":                                        http.StatusUnauthorized,
		"/truenas/api/v2.0/pool/filesystem_choices":                                    http.StatusUnauthorized,
		"/truenas/api/v2.0/pool/id/{id}/get_disks":                                     http.StatusUnauthorized,
		"/truenas/api/v2.0/pool/get_instance_by_name":                                  http.StatusUnauthorized,
		"/truenas/api/v2.0/pool/import_disk":                                           http.StatusUnauthorized,
		"/truenas/api/v2.0/pool/import_disk_autodetect_fs_type":                        http.StatusUnauthorized,
		"/truenas/api/v2.0/pool/import_pool":                                           http.StatusUnauthorized,
		"/truenas/api/v2.0/pool/id/{id}/is_upgraded":                                   http.StatusUnauthorized,
		"/truenas/api/v2.0/pool/id/{id}/offline":                                       http.StatusUnauthorized,
		"/truenas/api/v2.0/pool/id/{id}/online":                                        http.StatusUnauthorized,
		"/truenas/api/v2.0/pool/id/{id}/processes":                                     http.StatusUnauthorized,
		"/truenas/api/v2.0/pool/id/{id}/remove":                                        http.StatusUnauthorized,
		"/truenas/api/v2.0/pool/id/{id}/replace":                                       http.StatusUnauthorized,
		"/truenas/api/v2.0/pool/id/{id}/scrub":                                         http.StatusUnauthorized,
		"/truenas/api/v2.0/pool/id/{id}/upgrade":                                       http.StatusUnauthorized,
		"/truenas/api/v2.0/pool/dataset":                                               http.StatusUnauthorized,
		"/truenas/api/v2.0/pool/dataset/id/{id}/attachments":                           http.StatusUnauthorized,
		"/truenas/api/v2.0/pool/dataset/change_key":                                    http.StatusUnauthorized,
		"/truenas/api/v2.0/pool/dataset/destroy_snapshots":                             http.StatusUnauthorized,
		"/truenas/api/v2.0/pool/dataset/encryption_summary":                            http.StatusUnauthorized,
		"/truenas/api/v2.0/pool/dataset/export_key":                                    http.StatusUnauthorized,
		"/truenas/api/v2.0/pool/dataset/export_keys":                                   http.StatusUnauthorized,
		"/truenas/api/v2.0/pool/dataset/id/{id}/get_quota":                             http.StatusUnauthorized,
		"/truenas/api/v2.0/pool/dataset/inherit_parent_encryption_properties":          http.StatusUnauthorized,
		"/truenas/api/v2.0/pool/dataset/lock":                                          http.StatusUnauthorized,
		"/truenas/api/v2.0/pool/dataset/id/{id}/permission":                            http.StatusUnauthorized,
		"/truenas/api/v2.0/pool/dataset/id/{id}/processes":                             http.StatusUnauthorized,
		"/truenas/api/v2.0/pool/dataset/id/{id}/promote":                               http.StatusUnauthorized,
		"/truenas/api/v2.0/pool/dataset/recommended_zvol_blocksize":                    http.StatusUnauthorized,
		"/truenas/api/v2.0/pool/dataset/id/{id}/set_quota":                             http.StatusUnauthorized,
		"/truenas/api/v2.0/pool/dataset/unlock":                                        http.StatusUnauthorized,
		"/truenas/api/v2.0/pool/dataset/unlock_services_restart_choices":               http.StatusUnauthorized,
		"/truenas/api/v2.0/pool/dataset/userprop":                                      http.StatusUnauthorized,
		"/truenas/api/v2.0/pool/scrub":                                                 http.StatusUnauthorized,
		"/truenas/api/v2.0/pool/scrub/run":                                             http.StatusUnauthorized,
		"/truenas/api/v2.0/pool/scrub/scrub":                                           http.StatusUnauthorized,
		"/truenas/api/v2.0/pool/snapshottask":                                          http.StatusUnauthorized,
		"/truenas/api/v2.0/pool/snapshottask/id/{id}/delete_will_change_retention_for": http.StatusUnauthorized,
		"/truenas/api/v2.0/pool/snapshottask/foreseen_count":                           http.StatusUnauthorized,
		"/truenas/api/v2.0/pool/snapshottask/id/{id}/run":                              http.StatusUnauthorized,
		"/truenas/api/v2.0/pool/snapshottask/id/{id}/update_will_change_retention_for": http.StatusUnauthorized,
		"/truenas/api/v2.0/replication":                                                http.StatusUnauthorized,
		"/truenas/api/v2.0/replication/count_eligible_manual_snapshots":                http.StatusUnauthorized,
		"/truenas/api/v2.0/replication/create_dataset":                                 http.StatusUnauthorized,
		"/truenas/api/v2.0/replication/list_datasets":                                  http.StatusUnauthorized,
		"/truenas/api/v2.0/replication/id/{id}/restore":                                http.StatusUnauthorized,
		"/truenas/api/v2.0/replication/id/{id}/run":                                    http.StatusUnauthorized,
		"/truenas/api/v2.0/replication/run_onetime":                                    http.StatusUnauthorized,
		"/truenas/api/v2.0/replication/target_unmatched_snapshots":                     http.StatusUnauthorized,
		"/truenas/api/v2.0/reporting/get_data":                                         http.StatusUnauthorized,
		"/truenas/api/v2.0/route/ipv4gw_reachable":                                     http.StatusUnauthorized,
		"/truenas/api/v2.0/rsyncmod":                                                   http.StatusUnauthorized,
		"/truenas/api/v2.0/rsynctask":                                                  http.StatusUnauthorized,
		"/truenas/api/v2.0/rsynctask/id/{id}/run":                                      http.StatusUnauthorized,
		"/truenas/api/v2.0/service/reload":                                             http.StatusUnauthorized,
		"/truenas/api/v2.0/service/restart":                                            http.StatusUnauthorized,
		"/truenas/api/v2.0/service/start":                                              http.StatusUnauthorized,
		"/truenas/api/v2.0/service/started":                                            http.StatusUnauthorized,
		"/truenas/api/v2.0/service/started_or_enabled":                                 http.StatusUnauthorized,
		"/truenas/api/v2.0/service/stop":                                               http.StatusUnauthorized,
		"/truenas/api/v2.0/service/terminate_process":                                  http.StatusUnauthorized,
		"/truenas/api/v2.0/sharing/nfs":                                                http.StatusUnauthorized,
		"/truenas/api/v2.0/sharing/smb":                                                http.StatusUnauthorized,
		"/truenas/api/v2.0/sharing/webdav":                                             http.StatusUnauthorized,
		"/truenas/api/v2.0/smart/test":                                                 http.StatusUnauthorized,
		"/truenas/api/v2.0/smart/test/disk_choices":                                    http.StatusUnauthorized,
		"/truenas/api/v2.0/smart/test/manual_test":                                     http.StatusUnauthorized,
		"/truenas/api/v2.0/smb/get_remote_acl":                                         http.StatusUnauthorized,
		"/truenas/api/v2.0/smb/status":                                                 http.StatusUnauthorized,
		"/truenas/api/v2.0/smb/sharesec":                                               http.StatusUnauthorized,
		"/truenas/api/v2.0/smb/sharesec/getacl":                                        http.StatusUnauthorized,
		"/truenas/api/v2.0/staticroute":                                                http.StatusUnauthorized,
		"/truenas/api/v2.0/stats/get_data":                                             http.StatusUnauthorized,
		"/truenas/api/v2.0/stats/get_dataset_info":                                     http.StatusUnauthorized,
		"/truenas/api/v2.0/support/attach_ticket":                                      http.StatusUnauthorized,
		"/truenas/api/v2.0/support/fetch_categories":                                   http.StatusUnauthorized,
		"/truenas/api/v2.0/support/new_ticket":                                         http.StatusUnauthorized,
		"/truenas/api/v2.0/system/feature_enabled":                                     http.StatusUnauthorized,
		"/truenas/api/v2.0/system/license_update":                                      http.StatusUnauthorized,
		"/truenas/api/v2.0/system/reboot":                                              http.StatusUnauthorized,
		"/truenas/api/v2.0/system/shutdown":                                            http.StatusUnauthorized,
		"/truenas/api/v2.0/system/general/ui_restart":                                  http.StatusUnauthorized,
		"/truenas/api/v2.0/system/ntpserver":                                           http.StatusUnauthorized,
		"/truenas/api/v2.0/truenas/set_production":                                     http.StatusUnauthorized,
		"/truenas/api/v2.0/truenas/update_customer_information":                        http.StatusUnauthorized,
		"/truenas/api/v2.0/tunable":                                                    http.StatusUnauthorized,
		"/truenas/api/v2.0/update/check_available":                                     http.StatusUnauthorized,
		"/truenas/api/v2.0/update/file":                                                http.StatusUnauthorized,
		"/truenas/api/v2.0/update/get_pending":                                         http.StatusUnauthorized,
		"/truenas/api/v2.0/update/manual":                                              http.StatusUnauthorized,
		"/truenas/api/v2.0/update/set_auto_download":                                   http.StatusUnauthorized,
		"/truenas/api/v2.0/update/set_train":                                           http.StatusUnauthorized,
		"/truenas/api/v2.0/update/update":                                              http.StatusUnauthorized,
		"/truenas/api/v2.0/user":                                                       http.StatusUnauthorized,
		"/truenas/api/v2.0/user/get_user_obj":                                          http.StatusUnauthorized,
		"/truenas/api/v2.0/user/id/{id}/pop_attribute":                                 http.StatusUnauthorized,
		"/truenas/api/v2.0/user/id/{id}/set_attribute":                                 http.StatusUnauthorized,
		"/truenas/api/v2.0/user/shell_choices":                                         http.StatusUnauthorized,
		"/truenas/api/v2.0/vm":                                                         http.StatusUnauthorized,
		"/truenas/api/v2.0/vm/id/{id}/clone":                                           http.StatusUnauthorized,
		"/truenas/api/v2.0/vm/get_available_memory":                                    http.StatusUnauthorized,
		"/truenas/api/v2.0/vm/get_console":                                             http.StatusUnauthorized,
		"/truenas/api/v2.0/vm/get_display_devices":                                     http.StatusUnauthorized,
		"/truenas/api/v2.0/vm/get_memory_usage":                                        http.StatusUnauthorized,
		"/truenas/api/v2.0/vm/get_vm_memory_info":                                      http.StatusUnauthorized,
		"/truenas/api/v2.0/vm/id/{id}/poweroff":                                        http.StatusUnauthorized,
		"/truenas/api/v2.0/vm/id/{id}/restart":                                         http.StatusUnauthorized,
		"/truenas/api/v2.0/vm/id/{id}/start":                                           http.StatusUnauthorized,
		"/truenas/api/v2.0/vm/id/{id}/status":                                          http.StatusUnauthorized,
		"/truenas/api/v2.0/vm/id/{id}/stop":                                            http.StatusUnauthorized,
		"/truenas/api/v2.0/vm/device":                                                  http.StatusUnauthorized,
		"/truenas/api/v2.0/vm/device/passthrough_device":                               http.StatusUnauthorized,
		"/truenas/api/v2.0/vmware":                                                     http.StatusUnauthorized,
		"/truenas/api/v2.0/vmware/dataset_has_vms":                                     http.StatusUnauthorized,
		"/truenas/api/v2.0/vmware/get_datastores":                                      http.StatusUnauthorized,
		"/truenas/api/v2.0/vmware/get_virtual_machines":                                http.StatusUnauthorized,
		"/truenas/api/v2.0/vmware/match_datastores_with_datasets":                      http.StatusUnauthorized,
		"/truenas/api/v2.0/webui/image":                                                http.StatusUnauthorized,
		"/truenas/api/v2.0/zfs/snapshot":                                               http.StatusUnauthorized,
		"/truenas/api/v2.0/zfs/snapshot/clone":                                         http.StatusUnauthorized,
		"/truenas/api/v2.0/zfs/snapshot/remove":                                        http.StatusUnauthorized,
		"/truenas/api/v2.0/zfs/snapshot/rollback":                                      http.StatusUnauthorized,
	},
	http.MethodPut: {
		"/truenas/api/v2.0/acme/dns/authenticator/id/{id}": http.StatusUnauthorized,
		"/truenas/api/v2.0/activedirectory":                http.StatusUnauthorized,
		"/truenas/api/v2.0/alertclasses":                   http.StatusUnauthorized,
		"/truenas/api/v2.0/alertservice/id/{id}":           http.StatusUnauthorized,
		"/truenas/api/v2.0/api_key/id/{id}":                http.StatusUnauthorized,
		"/truenas/api/v2.0/auth/twofactor":                 http.StatusUnauthorized,
		"/truenas/api/v2.0/bootenv/id/{id}":                http.StatusUnauthorized,
		"/truenas/api/v2.0/catalog/id/{id}":                http.StatusUnauthorized,
		"/truenas/api/v2.0/certificate/id/{id}":            http.StatusUnauthorized,
		"/truenas/api/v2.0/certificateauthority/id/{id}":   http.StatusUnauthorized,
		"/truenas/api/v2.0/chart/release/id/{id}":          http.StatusUnauthorized,
		"/truenas/api/v2.0/cloudsync/id/{id}":              http.StatusUnauthorized,
		"/truenas/api/v2.0/cloudsync/credentials/id/{id}":  http.StatusUnauthorized,
		"/truenas/api/v2.0/container":                      http.StatusUnauthorized,
		"/truenas/api/v2.0/cronjob/id/{id}":                http.StatusUnauthorized,
		"/truenas/api/v2.0/ctdb/private/ips/id/{id}":       http.StatusUnauthorized,
		"/truenas/api/v2.0/disk/id/{id}":                   http.StatusUnauthorized,
		"/truenas/api/v2.0/dyndns":                         http.StatusUnauthorized,
		"/truenas/api/v2.0/enclosure/id/{id}":              http.StatusUnauthorized,
		"/truenas/api/v2.0/failover":                       http.StatusUnauthorized,
		"/truenas/api/v2.0/filesystem/acltemplate/id/{id}": http.StatusUnauthorized,
		"/truenas/api/v2.0/ftp":                            http.StatusUnauthorized,
		"/truenas/api/v2.0/group/id/{id}":                  http.StatusUnauthorized,
		"/truenas/api/v2.0/idmap/id/{id}":                  http.StatusUnauthorized,
		"/truenas/api/v2.0/initshutdownscript/id/{id}":     http.StatusUnauthorized,
		"/truenas/api/v2.0/interface/id/{id}":              http.StatusUnauthorized,
		"/truenas/api/v2.0/ipmi/id/{id}":                   http.StatusUnauthorized,
		"/truenas/api/v2.0/iscsi/auth/id/{id}":             http.StatusUnauthorized,
		"/truenas/api/v2.0/iscsi/extent/id/{id}":           http.StatusUnauthorized,
		"/truenas/api/v2.0/iscsi/global":                   http.StatusUnauthorized,
		"/truenas/api/v2.0/iscsi/host/id/{id}":             http.StatusUnauthorized,
		"/truenas/api/v2.0/iscsi/initiator/id/{id}":        http.StatusUnauthorized,
		"/truenas/api/v2.0/iscsi/portal/id/{id}":           http.StatusUnauthorized,
		"/truenas/api/v2.0/iscsi/target/id/{id}":           http.StatusUnauthorized,
		"/truenas/api/v2.0/iscsi/targetextent/id/{id}":     http.StatusUnauthorized,
		"/truenas/api/v2.0/kerberos":                       http.StatusUnauthorized,
		"/truenas/api/v2.0/kerberos/keytab/id/{id}":        http.StatusUnauthorized,
		"/truenas/api/v2.0/kerberos/realm/id/{id}":         http.StatusUnauthorized,
		"/truenas/api/v2.0/keychaincredential/id/{id}":     http.StatusUnauthorized,
		"/truenas/api/v2.0/kmip":                           http.StatusUnauthorized,
		"/truenas/api/v2.0/kubernetes":                     http.StatusUnauthorized,
		"/truenas/api/v2.0/ldap":                           http.StatusUnauthorized,
		"/truenas/api/v2.0/lldp":                           http.StatusUnauthorized,
		"/truenas/api/v2.0/mail":                           http.StatusUnauthorized,
		"/truenas/api/v2.0/network/configuration":          http.StatusUnauthorized,
		"/truenas/api/v2.0/nfs":                            http.StatusUnauthorized,
		"/truenas/api/v2.0/openvpn/client":                 http.StatusUnauthorized,
		"/truenas/api/v2.0/openvpn/server":                 http.StatusUnauthorized,
		"/truenas/api/v2.0/pool/id/{id}":                   http.StatusUnauthorized,
		"/truenas/api/v2.0/pool/dataset/id/{id}":           http.StatusUnauthorized,
		"/truenas/api/v2.0/pool/dataset/userprop/id/{id}":  http.StatusUnauthorized,
		"/truenas/api/v2.0/pool/resilver":                  http.StatusUnauthorized,
		"/truenas/api/v2.0/pool/scrub/id/{id}":             http.StatusUnauthorized,
		"/truenas/api/v2.0/pool/snapshottask/id/{id}":      http.StatusUnauthorized,
		"/truenas/api/v2.0/replication/id/{id}":            http.StatusUnauthorized,
		"/truenas/api/v2.0/replication/config":             http.StatusUnauthorized,
		"/truenas/api/v2.0/reporting":                      http.StatusUnauthorized,
		"/truenas/api/v2.0/rsyncd":                         http.StatusUnauthorized,
		"/truenas/api/v2.0/rsyncmod/id/{id}":               http.StatusUnauthorized,
		"/truenas/api/v2.0/rsynctask/id/{id}":              http.StatusUnauthorized,
		"/truenas/api/v2.0/s3":                             http.StatusUnauthorized,
		"/truenas/api/v2.0/service/id/{id}":                http.StatusUnauthorized,
		"/truenas/api/v2.0/sharing/nfs/id/{id}":            http.StatusUnauthorized,
		"/truenas/api/v2.0/sharing/smb/id/{id}":            http.StatusUnauthorized,
		"/truenas/api/v2.0/sharing/webdav/id/{id}":         http.StatusUnauthorized,
		"/truenas/api/v2.0/smart":                          http.StatusUnauthorized,
		"/truenas/api/v2.0/smart/test/id/{id}":             http.StatusUnauthorized,
		"/truenas/api/v2.0/smb":                            http.StatusUnauthorized,
		"/truenas/api/v2.0/smb/sharesec/id/{id}":           http.StatusUnauthorized,
		"/truenas/api/v2.0/snmp":                           http.StatusUnauthorized,
		"/truenas/api/v2.0/ssh":                            http.StatusUnauthorized,
		"/truenas/api/v2.0/staticroute/id/{id}":            http.StatusUnauthorized,
		"/truenas/api/v2.0/support":                        http.StatusUnauthorized,
		"/truenas/api/v2.0/system/advanced":                http.StatusUnauthorized,
		"/truenas/api/v2.0/system/general":                 http.StatusUnauthorized,
		"/truenas/api/v2.0/system/ntpserver/id/{id}":       http.StatusUnauthorized,
		"/truenas/api/v2.0/systemdataset":                  http.StatusUnauthorized,
		"/truenas/api/v2.0/tftp":                           http.StatusUnauthorized,
		"/truenas/api/v2.0/truecommand":                    http.StatusUnauthorized,
		"/truenas/api/v2.0/tunable/id/{id}":                http.StatusUnauthorized,
		"/truenas/api/v2.0/ups":                            http.StatusUnauthorized,
		"/truenas/api/v2.0/user/id/{id}":                   http.StatusUnauthorized,
		"/truenas/api/v2.0/vm/id/{id}":                     http.StatusUnauthorized,
		"/truenas/api/v2.0/vm/device/id/{id}":              http.StatusUnauthorized,
		"/truenas/api/v2.0/vmware/id/{id}":                 http.StatusUnauthorized,
		"/truenas/api/v2.0/webdav":                         http.StatusUnauthorized,
		"/truenas/api/v2.0/zfs/snapshot/id/{id}":           http.StatusUnauthorized,
	},
}
